### PR TITLE
(maint) Do not merge - latest build retrieval

### PR DESCRIPTION
**Pull request by luchihoratiu**

### CODE REVIEW

**Comment by luchihoratiu** [comment]
Jenkins please test this on aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,fedora32-64a,osx1014-64a,osx1015-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-AARCH64a,redhat8-64a,redhat8-AARCH64a,redhatfips7-64a,sles12-64a,sles15-64a,solaris11-64a,solaris11-SPARCa,solaris114-64a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,ubuntu2004-AARCH64a,windows10ent-64a,windows10ent-32a,windows2012r2-64a,windows2019_ja-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by luchihoratiu** [comment]
Jenkins please test this on aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,fedora32-64a,osx1014-64a,osx1015-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-AARCH64a,redhat8-64a,redhat8-AARCH64a,redhatfips7-64a,sles12-64a,sles15-64a,solaris11-64a,solaris11-SPARCa,solaris114-64a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,ubuntu2004-AARCH64a,windows10ent-64a,windows10ent-32a,windows2012r2-64a,windows2019_ja-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by gimmyxd** [comment]
This won't work as for facter-ng we use released facter versions. The latest release does not contain the needed changes: https://github.com/puppetlabs/puppet-agent/blob/6.x/configs/components/facter-ng.rb#L2-L4

**Comment by luchihoratiu** [comment]
Jenkins please test this on aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,fedora32-64a,osx1014-64a,osx1015-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-AARCH64a,redhat8-64a,redhat8-AARCH64a,redhatfips7-64a,sles12-64a,sles15-64a,solaris11-64a,solaris11-SPARCa,solaris114-64a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,ubuntu2004-AARCH64a,windows10ent-64a,windows10ent-32a,windows2012r2-64a,windows2019_ja-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by luchihoratiu** [comment]
Jenkins please test this on aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,fedora32-64a,osx1014-64a,osx1015-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-AARCH64a,redhat8-64a,redhat8-AARCH64a,redhatfips7-64a,sles12-64a,sles15-64a,solaris11-64a,solaris11-SPARCa,solaris114-64a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,ubuntu2004-AARCH64a,windows10ent-64a,windows10ent-32a,windows2012r2-64a,windows2019_ja-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Pull request closed without merging**
