### PR TITLE
(PA-4313) Install hiera gemspec on Windows

### PR DESCRIPTION
**Pull request by joshcooper**

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this on windows2019-64a,windows10ent-32a

**Comment by joshcooper** [comment]
jenkins please test this on windows2019-64a,windows10ent-32a

**Comment by joshcooper** [comment]
puppet-agent 7f521c2b808c3006c42a94ec679ef728d331e42b

**Comment by cthorn42** [comment]
This looks good, tested this out on a windows build and the hiera gemspec is now appearing on Windows.

**Pull request merged**
