### PR TITLE
(CPR-391) Fedora packages have odd distro tags

### PR DESCRIPTION
**Pull request by mwaggett**
This PR 

- Removes EOL platform configs

- Explicitly sets `dist` for fedora platforms so that package names will go from something like `puppet-agent-1.9.1-1.fedoraf25.x86_64.rpm` to `puppet-agent-1.9.1-1.fc25.x86_64.rpm`.

- Renames fedora platforms (e.g. fedora-f25-x86_64 --> fedora-25-x86_64), which will result in a new directory structure (e.g. http://yum.puppetlabs.net/fedora/f25/PC1/... --> http://yum.puppetlabs.net/fedora/25/PC1/...).

We need to decide whether we want existing builds to stay where they are (under the existing `f<version>/` directory) or whether we want to move them (to under a new `<version>/`), and/or whether we want to create symlinks.

Relevant ticket(s): [CPR-391](https://tickets.puppetlabs.com/browse/CPR-391), [CPR-407](https://tickets.puppetlabs.com/browse/CPR-407), [CPR-408](https://tickets.puppetlabs.com/browse/CPR-408), [CPR-409](https://tickets.puppetlabs.com/browse/CPR-409)

### CODE REVIEW

**Comment by joshcooper** [comment]
Hi Molly, if this changes the filename when published to builds.delivery.pl.net, and there aren't symlinks to the old names, then it will break beaker (and puppet-agent pipelines). I would like to see something like https://tickets.puppetlabs.com/browse/RE-8333 implemented, so that we can change packaging over time without breaking consumers.

**Comment by mwaggett** [comment]
Built fedora packages with the shiny new path and dist tag: http://builds.delivery.puppetlabs.net/puppet-agent/979bb5994c849a954c85c8e76729b808e83c3add/artifacts/fedora/25/PC1/x86_64/

**Comment by Magisus** [comment]
This looks good to me, but want to verify this isn't going to break any tooling before merging.

**Comment by mwaggett** [comment]
Waiting for beaker's end of [RE-8333](https://tickets.puppetlabs.com/browse/RE-8333).

**Comment by mwaggett** [comment]
closing this and opening a new one since conflicts are hard

**Pull request closed without merging**
