### PR TITLE
(PA-2031) update build_defaults to use packaging 1.0.x

### PR DESCRIPTION
**Pull request by sarameisburger**
if nothing breaks we will hopefully be able to use packaging as a gem

### CODE REVIEW

**Comment by mwaggett** [comment]
@sarameisburger Have you tested this out at all?

**Comment by sarameisburger** [comment]
@mwaggett I tested it with a `rake pl:jenkins:retrieve` and looks to have retrieved properly. 

We'll want to hold off on merging this PR and #1422 for not a Friday

**Comment by sarameisburger** [comment]
@caseywilliams this is ready to go in!

**Comment by caseywilliams** [comment]
jenkins please test this

**Comment by sarameisburger** [comment]
Cool, once this goes in i'll re-point https://github.com/puppetlabs/puppet-agent/pull/1422 to 1.10.x and do merge ups

**Pull request merged**
