### PR TITLE
Merge 1.10.x -> 5.3.x

### PR DESCRIPTION
**Pull request by mwaggett**

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by McdonaldSeanp** [comment]
@mwaggett can you (or someone else) add release notes to https://tickets.puppetlabs.com/browse/PA-1546 to identify why we are doing this?

**Comment by mwaggett** [comment]
@McdonaldSeanp added - is that enough info?

**Comment by McdonaldSeanp** [comment]
@mwaggett yeah, that's good

**Pull request merged**
