### PR TITLE
(PA-633) Add acceptance testing setup for Puppet Agent

### PR DESCRIPTION
**Pull request by MosesMendoza**
This PR adds the ability to add and run acceptance tests to Puppet Agent.

Prior to this PR, Puppet Agent could only be tested by running acceptance tests from its various components in 'package testing' (aio) mode, which indirectly tested that the packages themselves were sane. Unfortunately, this led to a number of problems, including:
- Much of the package creation and manipulation logic is untested, which means it is currently difficult to know if changes will introduce regressions
- What package testing does exist has been spread out across repos including puppet and beaker, making it difficult to find, augment, and maintain
- We don't have any automated testing to validate that our shipped packages are viable/usable by users

This PR starts with the basic framework in use by the Puppet Agent components, that is:
- a Rakefile that defines tasks and methods which drive beaker
- a set of pre-suite setup tasks for installation and configuration of Puppet Agent
- a tests directory containing (in this PR) a single test which is a good candidate for one to move from Puppet to Puppet Agent

This PR deviates from the component acceptance tests:
- No 'gem' or 'git' acceptance testing is added (these are component-driven delivery mechanisms)
- Some obsolete workaround logic has been removed
The majority of differences exist in `acceptance/Rakefile` and `acceptance/setup/aio/pre-suite/010_Install.rb`.
- Perhaps most notably this PR doesn't actually (yet) test the source of puppet agent or support testing a local cache of built package artifacts. Rather, it assumes that packages of the version specified to test via ENV['SHA'] exist on one of the supported package delivery mechanisms - `builds.delivery.puppetlabs.net` (puppet internal), `nightlies.puppetlabs.com` (public), or our production download repositories/site (public). If these tests are added to the end of the existing Puppet Agent test pipeline, this should always be true as earlier steps in the pipeline generate PA artifacts to test from. This is a substantial TODO that needs ticketed.

Usage
As documented in the `acceptance/README.md` in the PR, usage is drive by rake:
`rake acceptance:development`
- Run acceptance tests against Puppet Agent packages on unreleased repos (ie builds.delivery.puppetlabs.net for internal and nightlies.puppet.com for public)
`rake acceptance:released`
- Run acceptance tests against Puppet Agent packages from released packages existing on our production Puppet repos, ie yum.puppetlabs.com. This will allow us to validate that our shipped production packages are sane.

For more info on the specific configuration/environment variables supported see the README.md.

Out of scope from this PR is describing how frequently and when P-A acceptance tests will be run, adding this to CI, or additional scouring of repos to pull out tests that really belong in this one. That needs to be ticketed separately.

### CODE REVIEW

**Comment by MosesMendoza** [comment]
This PR supersedes #904

**Comment by branan** [comment]
@MosesMendoza what's up with the rubocop stuff? It'd be nice to get that clean - It looks like we probably need to add some exemptions for the acceptance/ directory?

**Comment by MosesMendoza** [comment]
@branan yes - in our other projects we exclude `acceptance` as our syntax for beaker tests isn't compatible. Added.

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
