### PR TITLE
(maint) Update Leatherman to 0.7.4

### PR DESCRIPTION
**Pull request by MikaelSmith**
Introduces the fix for LTH-99.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Some of the changes from 0.7.3 are needed in puppet-agent; might as well bump it to 0.7.4.

**Comment by geoffnichols** [comment]
👍

**Comment by McdonaldSeanp** [comment]
Matrix build running at http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/507/

**Comment by McdonaldSeanp** [comment]
Nothing seems out of place

**Pull request merged**
