### PR TITLE
(maint) Add zfs_core module to PA

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this with agent master

**Comment by branan** [comment]
Please use a PA ticket. Our release tooling gets sad when it can't associate tickets with the right fixversions in Jira

**Comment by melissa** [comment]
I've removed the reference to a PUP ticket in the title

**Comment by melissa** [comment]
@branan since this PR references a sub-ticket, I can't move that ticket to the PA project. Is this a sufficient commit title to get this merged in?

**Comment by branan** [comment]
Yeah, good enough for the ticket management tools to not be sad. Ideally we'd have a ticket in the git history to track the work on this end, but it's not the end of the world. This is one of the many reasons I don't like Jira subtasks

**Comment by melissa** [comment]
I agree, but subtasks seemed like the best tool at the time :( I apparently hadn't learned my lesson from the previous times I've been bitten by subtasks

**Pull request merged**
