### PR TITLE
(maint) merge 1.10.x -> 5.3.x

### PR DESCRIPTION
**Pull request by McdonaldSeanp**

### CODE REVIEW

**Comment by branan** [comment]
AIX 5.3 was already removed from the Puppet-agent 5 series, so it's expected to be missing from this mergeup :+1:

**Comment by McdonaldSeanp** [comment]
@ekinanp we will do those in a separate PR

**Comment by branan** [comment]
We'll take care of that in a seprate PR once we've fixed up the jenkins jobs to no longer build/test those platforms. This just disables our automation around shipping those artifacts to the outside world

**Comment by ekinanp** [comment]
Thanks for the clarification. Then this LGTM.

**Pull request merged**
