### PR TITLE
(PA-1502) Set NoAppConsole=1 for Win-10 Creators

### PR DESCRIPTION
**Pull request by jcoconnor**
Win-10 Creators has an issue with nssm startup that is address by
setting NoAppConsole=1

### CODE REVIEW

**Comment by jcoconnor** [comment]
I have successfully built this and installed the agent on a ```win-10``` machine with ```Windows 10 Enterprise, version 1703``` (Creators).

Once puppet is configured and connected to a pe-master ```pxp-agent``` appears to run ok.

**Comment by jcoconnor** [comment]
I have also tested this package on the following vmpooler templates:
1. win-2008r2-x86_64
2. win-2012r2-x86_64
3. win-2016-x86_64
4. win-7-x86_64

```pxp-agent``` startes on all machines (once they negotiate with a master) and successfully executed a ```puppet-run``` from the master.

**Comment by MikaelSmith** [comment]
This is marked critical, should we target at 5.3.x?

**Comment by Iristyle** [comment]
I tried to just retarget the branch and merge to 5.3.x, but it has a number of additional commits.

@jcoconnor could you update the PR so that it has just your commit against 5.3.x and repush now?

**Comment by jcoconnor** [comment]
Closing this as #1180 replaces it (retargeted at 5.3.x)

**Pull request closed without merging**
