### PR TITLE
(PA-954) Pin Hiera, MCO, pxp-agent to tags

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
For the upcoming 1.9.2 release

### CODE REVIEW

**Comment by jcoconnor** [comment]
👍

**Comment by Magisus** [comment]
Note: some platforms will fail on Facter tests with this tag due to acceptance changes that landed after the previous tag. With that caveat, 👍

**Comment by McdonaldSeanp** [comment]
Facter has been moved back to a SHA so acceptance will pass. It is very low risk to ship the latest facter changes as a Z release and we will benefit from all green CI.

**Comment by Magisus** [comment]
Sounds good to me 👍

**Pull request merged**
