### PR TITLE
(PA-2031) Update puppet-agent to use packaging as a gem

### PR DESCRIPTION
**Pull request by sarameisburger**
Needs testing...~~I also need to make a puppet-agent specific ticket for this, when I do I will update the PR~~

### CODE REVIEW

**Comment by sarameisburger** [comment]
jenkins please test this

**Comment by caseywilliams** [comment]
This looks good to me, but ooc, what's the reasoning behind targeting it at 5.3.x rather than 1.10.x or 5.5.x?

**Comment by sarameisburger** [comment]
I thought 1.10.x used packaging branch master which I just checked and realized is not true. I can retarget!

**Comment by sarameisburger** [comment]
Ah ok I remember now. The gemfile says 1.10.x is on packaging 1.0.x (https://github.com/puppetlabs/puppet-agent/blob/1.10.x/Gemfile#L14) but ext/build_defaults says packaging branch master (https://github.com/puppetlabs/puppet-agent/blob/1.10.x/ext/build_defaults.yaml#L3) so we'll probably want to test out pointing build_defaults at 1.0.x before we implement packaging as a gem there @caseywilliams

**Comment by sarameisburger** [comment]
opened PR for that here https://github.com/puppetlabs/puppet-agent/pull/1460

**Comment by sarameisburger** [comment]
jenkins please test this

**Pull request merged**
