### PR TITLE
(WIP) (RE-6796) Add puppetlabs.ico file to Add/Remove Programs

### PR DESCRIPTION
**Pull request by jcoconnor**
Add the Puppetlabs Icon to the Add/Remove Programs (control panel).
Also ensure that it and the License.rtf file are placed in the misc
directory on the target installation.

Please note, there is still a remaining task to formally update the
LICENSE.rtf file to the present date (RE-6772)

### CODE REVIEW

**Comment by jcoconnor** [comment]
Comments appreciated, but want to hold of merging until Tuesday next as need to test that this runs correctly on the main PA build rather than the stripped down (MSI only) build.

**Comment by ferventcoder** [comment]
So the icon was included but not the RTF.

**Comment by jcoconnor** [comment]
@ferventcoder Have just pushed up a fix to this as it wasn't picking up the .rtf file correctly in the build.

**Comment by McdonaldSeanp** [comment]
:+1:

**Comment by melissa** [comment]
Would it be worthwhile to seperate the rft work into a seperate commit?

**Comment by McdonaldSeanp** [comment]
Merged at https://github.com/puppetlabs/puppet-agent/pull/606

**Pull request closed without merging**
