### PR TITLE
Merge master to stable for 1.4.0 release

### PR DESCRIPTION
**Pull request by shrug**
excluded all json files in config/components (except the new one)

### CODE REVIEW

**Comment by joshcooper** [comment]
:+1:

**Comment by ScottGarman** [comment]
:+1: Seems to have pulled in all my work to date on huaweios (which won't be in the 1.4.0 release, but 1.4.z).

**Comment by kylog** [comment]
LGTM.

**Comment by melissa** [comment]
:+1:

**Pull request merged**
