### PR TITLE
(maint) Include sles12 power machines in vendored ruby tests

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by ekinanp** [comment]
Ran the tests locally and they passed.

**Comment by McdonaldSeanp** [comment]
👍

**Comment by ekinanp** [comment]
power8-sles12-1.ops.puppetlabs.net (sles12-POWER-1) executed in 0.41 seconds
Begin teardown
End teardown
tests/validate_vendored_ruby.rb passed in 17.86 seconds
      Test Suite: tests @ 2017-11-07 10:31:00 -0800

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 17.86 seconds
      Average Test Time: 17.86 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

      - Specific Test Case Status -

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
