### PR TITLE
(RE-6903) Update banners & Icons to new branding

### PR DESCRIPTION
**Pull request by jcoconnor**
Apply the new branding assets to the installer banner pages and
installed icons.

### CODE REVIEW

**Comment by jcoconnor** [comment]
Have just unit tested this on installs.
These are the new install screens.
snip20160504_1
snip20160504_2
snip20160504_3
snip20160504_4
snip20160504_5
snip20160504_6
snip20160504_7

**Comment by jcoconnor** [comment]
Also changed "Puppet Labs" to "Puppet Inc" in the Control Panel->Add Remove Programs
This is ready for merge.

**Comment by underscorgan** [comment]
👍

**Comment by jdwelch** [comment]
👍

**Pull request merged**
