### PR TITLE
(PA-427) Fix cpp-hocon build errors

### PR DESCRIPTION
**Pull request by Magisus**
This re-adds the cpp-hocon build configuration.

Once cpp-hocon has been tagged with its updates, the ref can be changed, and this can be merged.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
What was the solution for Mac OS X?

**Comment by Magisus** [comment]
I'm actually not sure yet; this is up so that @geoffnichols can test his solution.

**Comment by Magisus** [comment]
@MikaelSmith On 10.11 we were able to just update XCode to the latest version, but on 10.9 and 10.10 we had to manually patch the memory header files.

**Comment by branan** [comment]
@MikaelSmith see https://github.com/puppetlabs/puppet-agent/pull/782 for the OSX fix.

**Comment by branan** [comment]
:+1: form me

**Comment by MikaelSmith** [comment]
Waiting for a thumbs-up or merge from @geoffnichols

**Pull request merged**
