### PR TITLE
(PA-736) Bump leatherman in master to 0.10.0

### PR DESCRIPTION
**Pull request by mruzicka**
Bump leatherman in master to the 0.10.0 release which brings in the following new features & changes:
- Solaris implementation of the `create_detached_process` execution option (execution of child processes in separate contracts) (LTH-120)
- Renamed `create_new_process_group` execution option to `create_detached_process` to make the concept more broadly applicable (LTH-120)

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@puppetlabs/puppet-agent-maintainers

**Comment by Magisus** [comment]
When pinning to a tag in puppet-agent, we have decided to prefer to spell out `refs/tags/<tag #>` just to be absolutely sure we're grabbing a tag and not some branch.

**Comment by MikaelSmith** [comment]
Updated.

**Comment by Magisus** [comment]
👍

**Pull request merged**
