### PR TITLE
(PA-4313) Install facter and hiera gemspecs on Windows

### PR DESCRIPTION
**Pull request by joshcooper**

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this on windows2019-64a,windows10ent-32a

**Comment by joshcooper** [comment]
main is missing both facter and hiera, while 6.x is only missing hiera, see PR #https://github.com/puppetlabs/puppet-agent/pull/2207

**Comment by joshcooper** [comment]
jenkins please test this on windows2019-64a,windows10ent-32a

**Comment by joshcooper** [comment]
jenkins please test this on windows2019-64a,windows10ent-32a

**Review by cthorn42 — APPROVED** [review]
Looks good, tested this out with a `win-2012r2-x86_64` VM and I'm seeing in the specifications directory hiera and facter are now listed.

**Pull request merged**
