### PR TITLE
(RE-7301) Update stomp gem to 1.4.1

### PR DESCRIPTION
**Pull request by shrug**
Fixes certificate hostname verification

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
Can you do a matrix build for some canary platforms and include windows ?

**Comment by shrug** [comment]
Building at http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/491/

**Comment by shrug** [comment]
Looks green (there was an unrelated Fedora 14 failure)

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
