### PR TITLE
(PA-181) Explicitly specify -march for OS X builds

### PR DESCRIPTION
**Pull request by mckern**
This should explcitly target `core2` as the chipset to optimize for
at compilation time. That will hopefully help move along the
"illegal instruction" problem we've been seeing.

### CODE REVIEW

**Comment by mckern** [comment]
@stahnma We now have one confirmed report for "works on my machine," but I'd like a few more before we produce a signed build we let customers test.

**Comment by geoffnichols** [comment]
@mckern If you point me to a build, I can run upstairs and test it.

**Comment by stahnma** [comment]
@geoffnichols http://hdrive.websages.com/stahnma/puppet-agent-1.3.5.414.g2d2f0b1-1.osx10.10.dmg

**Comment by groob** [comment]
@stahnma I've tested the above installer on a several 2010 iMacs which were previously affected by the issue. Looks good here. 
Will there be an updated version of the OS X 10.11 build once the PR is merged?

**Comment by stahnma** [comment]
@groob awesome!  We need to do a bit more testing, but then we'll get this on the tree. After that, the builds should hit nightlies.puppetlabs.com (though they might miss 1.4.0, as that's being cut this week).

**Comment by MikaelSmith** [comment]
Any reason we're limiting it to the Facter component?

**Comment by mckern** [comment]
@MikaelSmith initially confining the change to one place specifically so that we have an easy canary for A/B testing viability. I was wondering about whether or not to make it a default for the entire platform though.

**Comment by MikaelSmith** [comment]
I would expect potential issues for all compiled applications; I'm not sure what's unique about Facter here.

**Comment by mckern** [comment]
@MikaelSmith CMake is what's unique. Almost everything else uses autotools.

**Comment by MikaelSmith** [comment]
Ah yes; then all the CMake-based projects should use it.

**Comment by arubdesu** [comment]
We've tested the above posted build on older hardware against our 2015.3 master and see basic functionality.

**Comment by stahnma** [comment]
@mckern what about pxp/pcp stuff? Shouldn't that have the same cmake options?

**Comment by mckern** [comment]
I'm going to apply these flags across the board for OS X builds and get an agent with that built.

**Comment by shrug** [comment]
:+1:  pending a test build

**Comment by mckern** [comment]
I have produced a working build from the revised `CFLAGS` (as defined at the project level, not the component level). These should be :ok_hand: to review and merge.

**Comment by stahnma** [comment]
@mckern have a build available?

**Comment by stahnma** [comment]
http://hdrive.websages.com/stahnma/puppet-agent-1.3.6.523.g85807c8-1.osx10.10.dmg

**Comment by groob** [comment]
Installed this new build on a few macs and checked facter, ruby and the puppet agent. Everything works as expected. If you'd like to test anything specific, I'd be happy to confirm. We have a few hundred affected machines here.

**Comment by shrug** [comment]
Still :+1:

**Pull request merged**
