### PR TITLE
(PA-1491) Add platform config for macOS 10.13.

### PR DESCRIPTION
**Pull request by geoffnichols**
Add platform config for macOS 10.13, using macOS 10.12 template.

### CODE REVIEW

**Comment by geoffnichols** [comment]
jenkins please test this on osx1013-64a

**Comment by geoffnichols** [comment]
jenkins please test all on osx1013-64a

**Comment by geoffnichols** [comment]
jenkins please test all on osx1013-64a

**Comment by geoffnichols** [comment]
jenkins please test all on osx1013-64

**Comment by geoffnichols** [comment]
jenkins please test this on osx1012-64,osx1013-64

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
