### PR TITLE
(maint) Add gettext-setup gem and dependencies

### PR DESCRIPTION
**Pull request by ahenroid**

### CODE REVIEW

**Comment by stahnma** [comment]
Have we had a license review on these?

**Comment by smcclellan** [comment]
@stahnma The dependencies/license are a subset of what razor-server uses (the code was derived from that). It wouldn't hurt to review again, I suppose.

**Comment by ahenroid** [comment]
I just opened a ticket with the release team.

**Comment by stahnma** [comment]
@ahenroid reviewing this again. We'd like to have the gems up on buildsources.delivery.pupeptlabs.net. You can use kerminator to make that happen `kerminator help mirrorsource`

**Comment by ahenroid** [comment]
When there is bandwidth, I'd like to get this going again. The gem sources are now pulled from buildsources.delivery.puppetlabs.net. However, I believe we're still waiting on the license review (RE-7690).

**Comment by shrug** [comment]
We need to update the URLs here to reference the upstream gems. The (fairly recent) rewrite functionality will handle using the internal mirrors. ping @mckern  for more info.

**Comment by shrug** [comment]
👍

**Pull request merged**
