### PR TITLE
(PA-1886) Remove gettext-setup gem

### PR DESCRIPTION
**Pull request by smcclellan**
Since this gem is no longer used for runtime tasks, it should be removed
as a dependency.

### CODE REVIEW

**Comment by smcclellan** [comment]
puppet-runtime PR is here: https://github.com/puppetlabs/puppet-runtime/pull/30

**Comment by ekinanp** [comment]
jenkins please test this

**Comment by ekinanp** [comment]
jenkins please test all

**Comment by ekinanp** [comment]
Wouldn't hurt to do a quick PR test before merging this

**Comment by branan** [comment]
Is it easier to just let this get removed by merging up the runtime changes, and just fix up the runtime for this ticket?

**Comment by smcclellan** [comment]
We'll make this change in the puppet-runtime PR instead.

**Pull request closed without merging**
