### PR TITLE
(PA-305) Build shared Leatherman libraries on Windows

### PR DESCRIPTION
**Pull request by MikaelSmith**
To support PCP-372, enable building shared libraries for Leatherman on
Windows.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Depends on https://github.com/puppetlabs/leatherman/pull/167 and https://github.com/puppetlabs/cpp-pcp-client/pull/152 being merged, and a new Leatherman release.

**Comment by stahnma** [comment]
👍

**Comment by MikaelSmith** [comment]
Dependencies are merged. I'll update this to point to a new Leatherman SHA. I'm tempted not to tag Leatherman yet, and let a nightly run verify it all works first.

**Comment by MikaelSmith** [comment]
Updated, trying out some test builds.

**Comment by MikaelSmith** [comment]
Our MSI layout makes using DLLs terrible :(. We end up duplicating the DLLs in Facter and pxp-agent.

@McdonaldSeanp this is ready

**Comment by MikaelSmith** [comment]
Another potential option for this would be to make cpp-pcp-client a static library on Windows and make the pxp-agent executable more self-contained.

**Comment by MikaelSmith** [comment]
ping @McdonaldSeanp

**Pull request merged**
