### PR TITLE
(maint) Bump Leatherman to 0.3.5

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
cc/ @MikaelSmith @branan

**Comment by MikaelSmith** [comment]
:+1:

**Comment by MikaelSmith** [comment]
I'll merge once packaging pipelines start passing again.

**Comment by MikaelSmith** [comment]
Facter pipeline passed: https://jenkins.puppetlabs.com/view/puppet-agent/view/master/view/facter/job/platform_facter_pkg-van-ship_master/17/

**Pull request merged**
