### PR TITLE
(RE-7397) Update libxml2 to 2.9.4

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by sarameisburger** [comment]
👍

**Comment by underscorgan** [comment]
does it blend?

**Comment by McdonaldSeanp** [comment]
Have you run it through any tests?

**Comment by McdonaldSeanp** [comment]
Oh heh, morgan got there first

**Comment by ScottGarman** [comment]
Can you build the huaweios target to make sure it doesn't blow up during the build process?

**Comment by melissa** [comment]
It builds, but I haven't run it through any tests. I've validated the new version does contain the fixes we want though.

I will build the huawei target now

**Pull request merged**
