### PR TITLE
(PA-1765) Use puppet-runtime to provide several dependencies

### PR DESCRIPTION
**Pull request by caseywilliams**
Uses puppet-runtime builds to provide the following dependencies:
- curl
- libedit
- libxml2
- libxslt
- openssl
- puppet-ca-bundle
- ruby
- all rubygems

This depends on https://github.com/puppetlabs/puppet-runtime/pull/5, which generates runtime tarballs for all branches of puppet-agent. 

This PR includes a new `puppet-runtime.rb` component which pulls in the runtime build and untars it in the root directory; This replaces all the removed components. I believe I've updated the [runtime PR](https://github.com/puppetlabs/puppet-runtime/pull/5) so that it contains all recent additions to the 1.10.x branch for these components, but a second set of eyes would be welcome.

This relies on the puppet-runtime repo having a tag with the version specified in the component (in this case, it's a tag in my puppet-runtime fork - we'll need to wait on the merging and tagging of https://github.com/puppetlabs/puppet-runtime/pull/5 before this PR works for the agent - I've been testing my builds using the [generic vanagon Jenkins job](http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1371/), though).

### CODE REVIEW

**Comment by caseywilliams** [comment]
Jenkins please test this on redhat7-64,ubuntu1604-POWER,windows2012r2-64,solaris10-SPARC,solaris11-64a,osx1011-64

**Comment by caseywilliams** [comment]
Jenkins please test this on redhat7-64,ubuntu1604-POWER,windows2012r2-64,solaris10-SPARC,solaris11-64a,osx1011-64

**Comment by caseywilliams** [comment]
The puppet-runtime package for these changes has built on Jenkins [here](https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_agent-runtime_vanagon-packaging_runtime-1.10.x/). I've rebased this PR with 1.10.x and updated the tag to point to the tarballs shipped today.

**Comment by caseywilliams** [comment]
jenkins please test this on aix61-POWER,aix71-POWER,aix72-POWER,amazon6-64,amazon7-64,arista4-32,ciscoxr-64 debian7-64,debian7-32,debian8-64,debian8-32,debian9-64,debian9-32,fedora25-64,fedora26-64,osx1010-64,osx1011-64,osx1012-64,redhat5-64,redhat6-64,redhat6-32,redhat7-64,redhat7-POWER,redhat7-AARCH64,sles11-64,sles11-32,sles12-64,sles12-POWER,solaris10-64,solaris10-SPARC,solaris11-64,solaris11-SPARC,ubuntu1404-64,ubuntu1404-32,ubuntu1604-64,ubuntu1604-32,ubuntu1604-POWER,windows10ent-32,windows2012r2-64

**Comment by caseywilliams** [comment]
jenkins please test this on all

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWER,aix71-POWER,,arista4-32,ciscoxr-64 debian7-64,debian7-32,debian8-64,debian8-32,debian9-64,debian9-32,osx1010-64,osx1011-64,osx1012-64,redhat5-64,redhat6-64,redhat6-32,redhat7-POWER,redhat7-AARCH64,sles11-64,sles11-32,sles12-64,sles12-POWER,solaris10-64,solaris11-64,ubuntu1404-64,ubuntu1404-32,ubuntu1604-32,ubuntu1604-POWER,windows2012r2-64

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWER,aix71-POWER,,arista4-32,ciscoxr-64 debian7-64,debian7-32,debian8-64,debian8-32,debian9-64,debian9-32,osx1010-64,osx1011-64,osx1012-64,redhat5-64,redhat6-64,redhat6-32,redhat7-POWER,redhat7-AARCH64,sles11-64,sles11-32,sles12-64,sles12-POWER,solaris10-64,solaris11-64,ubuntu1404-64,ubuntu1404-32,ubuntu1604-32,ubuntu1604-POWER,windows2012r2-64

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWER,aix71-POWER,ciscoxr-64,debian7-64,debian7-32,debian8-64,debian8-32,debian9-64,debian9-32,osx1010-64,osx1011-64,osx1012-64,redhat5-64,redhat6-64,redhat6-32,redhat7-POWER,redhat7-AARCH64,sles11-64,sles11-32,sles12-64,sles12-POWER,solaris10-64,solaris11-64,ubuntu1404-64,ubuntu1404-32,ubuntu1604-32,ubuntu1604-POWER,windows2012r2-64

**Comment by caseywilliams** [comment]
This passed an [ad-hoc](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/) build last night using a tag from my own puppet-runtime repo. I've just tagged the same commit in puppet-runtime proper and updated the reference here.

**Comment by underscorgan** [comment]
Hi, is there anything I can do to help move this along?

**Comment by caseywilliams** [comment]
@underscorgan Platform OS decided we'd like to get two things done before this moves forward:

- Updating the puppet-runtime pipeline jobs in CI to enable automatic tagging for puppet-runtime and automatic promotion into puppet-agent, and
- Moving the source of relevant settings from puppet-agent to puppet-runtime (so, reversing the direction of the settings import from agent -> runtime to runtime -> agent where it makes sense)

I may just close this PR for now and reopen once those things are done to reduce confusion. I'm hoping to wrap this all up early next week.

**Comment by underscorgan** [comment]
ok, cool. Thanks @caseywilliams !

**Pull request closed without merging**
