### PR TITLE
Update build_defaults.yaml rpm_targets for el-8

### PR DESCRIPTION
**Pull request by shrug**

### CODE REVIEW

**Comment by mwaggett** [comment]
Can you update the commit message to explain that this is needed for promotion to PE?

**Comment by mwaggett** [comment]
(also the repo is gonna yell about the formatting of your commit message anyway)

**Comment by shrug** [comment]
Yes, that's what I get for trying to use the github editor. turns out you can't update a commit after the initial edit.

**Comment by caseywilliams** [comment]
We haven't made the 6.4.x branch yet, but this should be in there. I'm inclined to merge it now and cherry-pick later, since we'd need to wait for pipelines to be created and merge up from 6.4.x to master if we targeted it there.

**Pull request merged**
