### PR TITLE
(maint) Update to leatherman 0.7.1

### PR DESCRIPTION
**Pull request by branan**
This is needed for puppetlabs/facter#1333

### CODE REVIEW

**Comment by branan** [comment]
Hold off on merging this, I might need to make a couple tweaks to PCP and PXP

**Comment by branan** [comment]
Looks like everything is good in PCP/PXP land, so I think this can go through.

**Comment by MikaelSmith** [comment]
👍

**Comment by branan** [comment]
Since we didn't merge this I'm going to update this PR for 0.7.1 and pretend 0.7.0 never happened

**Comment by MikaelSmith** [comment]
👍

**Pull request merged**
