### PR TITLE
(PA-350) Windows static libs with pxp-agent

### PR DESCRIPTION
**Pull request by MikaelSmith**
@McdonaldSeanp for your consideration. Relies on changes in cpp-pcp-client#master and pxp-agent#master.

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
Thanks @MikaelSmith , I'm going to look this over after we get the path reversion PR through

**Comment by MikaelSmith** [comment]
When that happens, there'll likely need to be a few more changes in `configs/components` in this PR.

**Comment by McdonaldSeanp** [comment]
All PRs should wait until we get a passing master again

**Comment by MikaelSmith** [comment]
@McdonaldSeanp thoughts on what needs to be updated now that your work is merged?

**Comment by MikaelSmith** [comment]
ping @McdonaldSeanp

**Comment by McdonaldSeanp** [comment]
@MikaelSmith I need to run a build to get you some details. we are a little bit all hands on deck for Ubuntu Xenial support right now, so I'll run a build tomorrow but I can't promise to get you anything meaningful until wednesday. however I will look in to this first thing wednesday to get you some feedback

**Comment by McdonaldSeanp** [comment]
@MikaelSmith from my perspective the build went well and things seem to be in order, even after the path revert. Which makes sense because this is not destructive behavior, it just statically links more stuff. I like the change and if you have tested it and it lives up to your standards, I am 👍

**Comment by MikaelSmith** [comment]
I haven't tested it much myself. I'll rebuild tomorrow and check it out.

**Comment by MikaelSmith** [comment]
Nevermind, this isn't needed. We only install one copy of DLLs and still use batch files to ensure we find all the dependencies.

**Pull request closed without merging**
