### PR TITLE
(maint) Add zone module to PA

### PR DESCRIPTION
**Pull request by joshcooper**
See PUP-8828

### CODE REVIEW

**Comment by joshcooper** [comment]
Corresponds to https://github.com/puppetlabs/puppetlabs-zone_core/tree/1.0.0

**Comment by joshcooper** [comment]
jenkins please test this on solaris11-64a,solaris10-64a

**Comment by melissa** [comment]
@joshcooper can you add zone to the list of modules in `configs/projects/puppet-agent.rb` as well?

**Comment by joshcooper** [comment]
good catch! updated.

**Comment by joshcooper** [comment]
jenkins please test this on solaris11-64a,solaris10-64a

**Pull request merged**
