### PR TITLE
(RE-6149) Build with Wix310

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by jcoconnor** [comment]
:+1:

**Comment by jcoconnor** [comment]
@melissa Have you successfully run a pipeline build on this - if so, please reference so it can be closed.
Change is straightforward enough (assuming no typos in 3.5/3.10 change which a build will expose).

**Comment by melissa** [comment]
I'm still testing. I'll ping people when testing is complete.

**Comment by melissa** [comment]
Built both architectures with the `build-windows.rb` script.

I also added installing wix during the vanagon build so we know we have the right wix version when we switch packaging formats. This change will add a little extra time to the build, but it shouldn't be a huge amount.

**Pull request merged**
