### PR TITLE
(maint) Remove puppetserver setup to reduce VM use

### PR DESCRIPTION
**Pull request by MikaelSmith**
Tests don't make use of a master, so stop setting one up.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
`be rake acceptance:development SHA=5.3.2`

```
...
              - Test Case Summary for suite 'tests' -
       Total Suite Time: 29.21 seconds
      Average Test Time: 14.61 seconds
              Attempted: 2
                 Passed: 2
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 2

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:

No tests to run for suite 'post_suite'
No tests to run for suite 'pre_cleanup'
Cleanup: cleaning up after successful run
ssh connection to redhat7-64-1 has been terminated
ssh connection to windows2012r2-64-1 has been terminated
Handing 't8dy1erl6v84sd2.delivery.puppetlabs.net' back to vmpooler for VM destruction
Handing 'upf970ie6fjlrtt.delivery.puppetlabs.net' back to vmpooler for VM destruction
Spent 0.14 seconds cleaning up
```

**Comment by MikaelSmith** [comment]
Should reduce our VM usage by 31 redhat machines for the full matrix, and reduce test time to <1 minute (except Windows) from 3-5 minutes.

**Comment by MikaelSmith** [comment]
Fixed, and still appears to run tests successfully.

**Comment by MikaelSmith** [comment]
Fixed.

**Comment by ekinanp** [comment]
This PR should be further reviewed and merged Monday to avoid affecting the weekend runs, as the current puppet agent pipelines have a TESTS_NEED_MASTER parameter for which puppet-agent is a part of.

**Comment by MikaelSmith** [comment]
Ah looks, like we'll want a separate PR after this is merged to drop that from CI config. It looks like it affects what we request from RMM.

**Comment by ekinanp** [comment]
Yep, that PR is already here: https://github.com/puppetlabs/ci-job-configs/pull/3701. Credit to @McdonaldSeanp for noting that and also waiting on the merge.

**Comment by MikaelSmith** [comment]
The CI config change impacts all pipelines, so this'll need to be merged up through them post-haste.

**Pull request merged**
