### PR TITLE
Merge cve branch to stable

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by Magisus** [comment]
Travis is failing because one of the tickets is internal.

**Comment by McdonaldSeanp** [comment]
Okay, this is good to merge then. Please ignore the failure in travis

**Comment by underscorgan** [comment]
Should there be any update to the pxp-agent component to make sure we're pulling in the latest version?

**Comment by McdonaldSeanp** [comment]
@underscorgan https://github.com/puppetlabs/pxp-agent/pull/499 is open, I was hoping to get this in, then merge that one and let the pipelines promote to stable

**Comment by underscorgan** [comment]
ok

**Pull request merged**
