### PR TITLE
(maint) Merge 5.5.x -> 6.0.x

### PR DESCRIPTION
**Pull request by mihaibuzgau**

### CODE REVIEW

**Comment by mihaibuzgau** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a

**Comment by denis-susan** [comment]
LGTM

**Comment by mihaibuzgau** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,fedora-29a

**Comment by mihaibuzgau** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,fedora29-64a

**Pull request merged**
