### PR TITLE
(PA-3772) Add RedHat 8 FIPS platform (6.x)

### PR DESCRIPTION
**Pull request by GabrielNagy**

### CODE REVIEW

**Comment by GabrielNagy** [comment]
jenkins please test this,puppet,pxp-agent on redhatfips8-64a

**Comment by GabrielNagy** [comment]
jenkins please test this,puppet,pxp-agent,facter on redhatfips8-64a

**Comment by GabrielNagy** [comment]
jenkins please test this,puppet,pxp-agent,facter on fedora32-64a,fedora34-64a,redhat6-64a,redhat6-32a,centos8-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhat8-POWERa,redhat8-AARCH64a,redhatfips7-64a,redhatfips8-64a

**Comment by GabrielNagy** [comment]
Acceptance passed apart from some transients on redhat7-POWERa:

image

I'm gonna rebase and drop the `puppet.json` commit, then this should be ready to go.

**Review by BobosilaVictor — APPROVED** [review]

**Pull request merged**
