### PR TITLE
(maint) facter-ng 4.0.40 version bump

### PR DESCRIPTION
**Pull request by florindragos**

### CODE REVIEW

**Comment by oanatmaria** [comment]
Jenkins please test this on all

**Comment by oanatmaria** [comment]
Jenkins please test this on all

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Comment by gimmyxd** [comment]
Solaris 10 sparc failure is unrelated and we are not running puppet-agent test for that in nightly. Not sure why we haven't seen that issue until now, maybe the test was working.

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Pull request closed without merging**
