### PR TITLE
(PA-1765) Use puppet-runtime to build puppet-agent

### PR DESCRIPTION
**Pull request by caseywilliams**
These changes move many of puppet agent's vendored components into a separate vanagon project, [puppetlabs/puppet-runtime](https://github.com/puppetlabs/puppet-runtime), and uses tarballs from builds of that project to provide those components here.

The first commit removes the following components and relies on a build of puppet-runtime to provide them instead:

- augeas
- curl
- libedit
- libxml2
- libxslt
- openssl
- puppet-ca-bundle
- ruby
- all rubygems

The second commit moves the source of truth for most build settings from puppet-agent to puppet-runtime, using vanagon's `import_settings` feature. On each build of puppet-agent, vanagon will clone puppet-runtime temporarily, copy its build settings, and use them as a basis for any further configuration in `configs/projects/puppet-agent.rb`. I've kept the settings that relate specifically to packaging the agent here (e.g. wix configuration, directories specific to agent components), but common settings like cflags have been moved to puppet-runtime.

Other notes:
- The contents of the preexisting `configs/components/runtime.rb` component are duplicated between the puppet-agent and puppet-runtime projects - its effects are required to build any C++ or ruby projects. 
    - This and the requirement to clone puppet-runtime on each build are two obvious drawbacks to applying the changes in this PR; I welcome advice for improvements.
- I've included the ability to use the system openssl instead of the agent's vendored version. This is required in higher agent branches (5.5.x, master) to successfully build for the redhat 7 FIPS platform (not included in this branch). The setting is only included here for convenience in merging up through those branches later, but I can move it into a separate commit applied later during mergeups if people prefer.

I'll run PR tests on this branch. I also did some manual mergeups through later branches and ran them through the ad-hoc pipeline successfully here: [5.3.x](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/112/), [5.5.x](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/113/), [master](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/114/).

### CODE REVIEW

**Comment by caseywilliams** [comment]
jenkins please test this on all

**Comment by caseywilliams** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian8-32a,debian9-64a,fedora25-64a,fedora27-64a,osx1010-64a,osx1011-64a,osx1012-64a,redhat5-64a,redhat6-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-POWERa,windows10ent-32a,windows2012r2-64a

**Comment by caseywilliams** [comment]
(Updated to appease rubocop)

**Comment by caseywilliams** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian8-32a,debian9-64a,fedora25-64a,fedora27-64a,osx1010-64a,osx1011-64a,osx1012-64a,redhat5-64a,redhat6-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-POWERa,windows10ent-32a,windows2012r2-64a

**Comment by caseywilliams** [comment]
I've added a commit to this PR that updates build instructions in the README (there have been no code changes)

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
