### PR TITLE
Mergup from 1.7.0-release

### PR DESCRIPTION
**Pull request by McdonaldSeanp**

### CODE REVIEW

**Comment by shrug** [comment]
What is the intended effect of doing the merge-up before the tag?

**Comment by McdonaldSeanp** [comment]
We would like to start doing mergeups as changes occur, as opposed to all at once after a tag.

**Comment by shrug** [comment]
Understood, I just don't see any changes...

As originally envisioned, changes would all land on stable and be cherry-picked to the release branch (except for the json file updates to pin to tags), so merge-ups would only be required to pick up tags. If we're going to be making changes in the release branch, then 👍 to merge-ups.

**Comment by McdonaldSeanp** [comment]
Yeah, there was a bunch that happened in the release branch so this is in order to keep history the same between release and stable. in the ideal world your thoughts are correct, the only mergedown will be the tag

**Pull request closed without merging**
