### PR TITLE
Pa 121/add vim syntax files

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
This PR will add vim syntax files in the P-A packaging under puppet/share/vim/puppet-vimfiles

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
This can't be merged until the correct vanagon is used in P-A. otherwise everything is going to fail.

**Comment by stahnma** [comment]
You could probably drop that merge commit.

**Comment by shermdog** [comment]
Looks legit to me.

**Comment by McdonaldSeanp** [comment]
There's currently a jenkins job running for this, wiat to merge until that is done

**Comment by McdonaldSeanp** [comment]
Okay, jenkins worked: http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/

**Comment by stahnma** [comment]
@joshcooper and @kylog wanted to call out the change to vanagon 0.5.0 here. We don't think this will break anything, but wanted to call it out.

**Comment by McdonaldSeanp** [comment]
Okay @stahnma is there anything you would like me to do to call it out?

**Comment by stahnma** [comment]
@McdonaldSeanp nope. We can merge this I think.

**Comment by kylog** [comment]
Thanks for the heads-up @stahnma. This seems like a good time to bump puppet-agent#master to a feature release of vanagon since we have ample runway to the next planned release off master.

**Pull request merged**
