### PR TITLE
(maint) Bump augeas to 1.0.3, see MODULES-8014

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by joshcooper** [comment]
jenkins please test this with agent 6.0.x

**Comment by joshcooper** [comment]
Fix for failing puppet-agent test in https://github.com/puppetlabs/puppet-agent/pull/1546

**Comment by joshcooper** [comment]
jenkins please test this with agent 6.0.x

**Comment by melissa** [comment]
jenkins please test this with agent 6.0.x

**Pull request merged**
