### PR TITLE
(PA-1698) Remove unsupported platforms (LTS)

### PR DESCRIPTION
**Pull request by caseywilliams**
Removes files and references for discontinued platforms:

- AIX 5.3
- Fedora 24
- Huawei - this includes the removal of its rubygem dependencies:
    - net-scp
    - net-ssh-telnet2
    - net-netconf
    - mini_portile2
    - nokogiri
    - pkg-config
- SLES 10
- Ubuntu 15.10 and 16.10

### CODE REVIEW

**Comment by caseywilliams** [comment]
jenkins please test this

**Comment by branan** [comment]
I imagine merging this up to 5.3.x is gonna be lots of fun

**Comment by caseywilliams** [comment]
Just updated to remove one last little reference to `powerpc-linux-gnu` in ruby-2.1.9 - I should mention that there are other PRs open to remove unused ruby versions, so that's not addressed here.

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWER

**Comment by caseywilliams** [comment]
Updated to resolve merge conflicts with 1.10.x

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWER

**Comment by McdonaldSeanp** [comment]
This PR LGTM, but we should wait to merge until we resolve the current failures in the 1.10.x pipeline

**Comment by caseywilliams** [comment]
Rebased with 1.10.x

**Comment by McdonaldSeanp** [comment]
jenkins please test this on all

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian7-32a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,fedora25-64a,fedora26-64a,osx1010-64a,osx1011-64a,osx1012-64a,osx1013-64a,redhat5-64a,redhat6-64a,redhat6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a

**Comment by McdonaldSeanp** [comment]
aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian7-32a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,osx1010-64a,osx1011-64a,osx1012-64a,osx1013-64a,redhat5-64a,redhat6-64a,redhat6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian7-32a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,osx1010-64a,osx1011-64a,osx1012-64a,osx1013-64a,redhat5-64a,redhat6-64a,redhat6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,amazon6-64a,amazon7-64a,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian7-32a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,osx1010-64a,osx1011-64a,osx1012-64a,redhat5-64a,redhat6-64a,redhat6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,amazon6-64a,amazon7-64a,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian7-32a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,osx1010-64a,osx1011-64a,osx1012-64a,redhat5-64a,redhat6-64a,redhat6-32a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-32a,ubuntu1604-POWERa,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian7-32a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,osx1010-64a,osx1011-64a,osx1012-64a,redhat5-64a,redhat6-64a,redhat6-32a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-32a,ubuntu1604-POWERa,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2012r2_ja-64a%7Blocale=ja%7D,windows2016-64a

**Comment by McdonaldSeanp** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,arista4-32a,ciscoxr-64a,cumulus25-64a,debian7-64a,debian7-32a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,osx1010-64a,osx1011-64a,osx1012-64a,redhat5-64a,redhat6-64a,redhat6-32a,redhat7-POWERa,redhat7-AARCH64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,solaris10-64a,solaris10-SPARCa,solaris11-64a,solaris11-SPARCa,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-32a,ubuntu1604-POWERa,windows2016-64a

**Comment by caseywilliams** [comment]
jenkins please test this on aix61-POWER,osx1011-64,redhat5-64,sles12-POWER,solaris10-i386,solaris-11-sparc,windows-2012r2-x64

**Comment by caseywilliams** [comment]
jenkins please test this on aix61-POWER,osx1011-64,redhat5-64,sles12-POWER,solaris10-32,solaris11-SPARC,windows-2012r2-x64

**Comment by caseywilliams** [comment]
jenkins please test this on aix61-POWER,osx1011-64,redhat5-64,sles12-POWER,solaris10-32,solaris11-SPARC,windows2012r2-64

**Pull request merged**
