### PR TITLE
(PA-2325) Add el-8-x86_64

### PR DESCRIPTION
**Pull request by gimmyxd**
I need to run the pipeline but seems that i have an issue with beaker-hostgenerator and the builds are not running.
Till then have a look and let me know what you think.
This is using @ekinanp changes from leatherman and build with GCC 8.2
Is dependent ob: https://tickets.puppetlabs.com/browse/PA-2334

### CODE REVIEW

**Comment by mihaibuzgau** [comment]
> @gimmyxd Any chance you could go ahead and clean-up Fedora 29 to use GCC 8 here too?

@ekinanp do you think there would be any value in redoing the Fedora 29 build ?

**Comment by gimmyxd** [comment]
@ekinanp i don't think it should be done here, it's not in the scope of PA-2325

**Comment by gimmyxd** [comment]
@ekinanp there is already a ticket for that https://tickets.puppetlabs.com/browse/PA-2362

**Comment by gimmyxd** [comment]
passing build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/

**Comment by gimmyxd** [comment]
Is dependent on: https://github.com/puppetlabs/puppet/pull/7307

**Comment by gimmyxd** [comment]
rerun the adhoc build(the last one is not available anymore)
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/

This is ready to be merged after puppet and puppet-runtime PR's are merged.

**Pull request merged**
