### PR TITLE
(maint) Update to leatherman 0.6.3

### PR DESCRIPTION
**Pull request by HAIL9000**
Update the leatherman version to 0.6.3 to reflect the new release

### CODE REVIEW

**Comment by MikaelSmith** [comment]
👍 Waiting on master CI to be green.

**Comment by MikaelSmith** [comment]
This should be a trivial change; the only changes from the prior SHA are tagging, setting the version, and release notes.

**Comment by MikaelSmith** [comment]
Oh, oops. @HAIL9000 can you update this to refer to `refs/tags/0.6.3`?

**Comment by MikaelSmith** [comment]
And it might make sense to put this against puppet-agent#stable and merge down.

**Comment by HAIL9000** [comment]
@MikaelSmith Sure thing, I'll update it and open a new PR against stable

**Pull request closed without merging**
