### PR TITLE
(PA-796) Update Ruby 2.3 component to 2.3.3

### PR DESCRIPTION
**Pull request by Magisus**
The latest version in the Ruby 2.3 series is 2.3.3. This commit updates
the existing Ruby 2.3.1 component to 2.3.3.

### CODE REVIEW

**Comment by Magisus** [comment]
This is blocked on the removal of AIX 5.3 from the agent build platforms.

**Comment by Magisus** [comment]
AIX 5.3 removed here: https://github.com/puppetlabs/ci-job-configs/pull/2454

**Comment by geoffnichols** [comment]
ping @puppetlabs/agent-platform-team for review

**Comment by branan** [comment]
Were the `rbconfig` files regenerated or just edited in place? I would /hope/ that just editing in place would work for a z bump, but Ruby is always super weird and I worry about these things...

**Comment by branan** [comment]
Also looks like the `README.md` still references 2.3.1.

**Comment by Magisus** [comment]
The `rbconfig` files had to be edited manually, but just changing the number in each of them seemed to work.

**Comment by ScottGarman** [comment]
I'm :+1: on this with the minor update to the README.md Branan just pointed out.

**Comment by Magisus** [comment]
Updated!

**Comment by McdonaldSeanp** [comment]
👍

**Pull request merged**
