### PR TITLE
(maint) Remove obsolete definitions for huaweios

### PR DESCRIPTION
**Pull request by ScottGarman**
This removes obsolete code referring to HuaweiOS when it was targeted for
WRL/RPM.

### CODE REVIEW

**Comment by mckern** [comment]
@ScottGarman are there any packages we should circle around and clean up as well or are we hanging on to those as historical artifacts?

:+1: on this.

**Comment by shermdog** [comment]
Looks like this should also be removed as part of this PR:  https://github.com/puppetlabs/puppet-agent/blob/master/configs/components/leatherman.rb#L7-L10

**Comment by stahnma** [comment]
no code is best code

**Comment by ScottGarman** [comment]
@shermdog that code is in puppet-agent master, and this PR is targeted at stable, so I'll have to create a separate PR to cull that bit.

@mckern I want to keep the WLR artifacts around for just a bit longer; demos that Huawei are doing could need to fall back to the WRL based environment until we've released the Debian based one.

**Comment by mckern** [comment]
@ScottGarman that makes sense. "Historical artifacts" it is!

**Pull request merged**
