### PR TITLE
(PA-1487) Update configuration of C components to include compiler

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
This commit updates the configuration of all C components to include the
compiler/rpath settings for linux platforms. Previously these were not
correctly set for Linux and we were using the system gcc

### CODE REVIEW

**Comment by ScottGarman** [comment]
I'm in favor of the spirit of these changes, but what this really needs is a large matrix of testing in the ad-hoc pipeline for all affected platforms.

**Comment by McdonaldSeanp** [comment]
@ScottGarman ask and you shall receive: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent_init-van-int_suite-daily-ad-hoc/165/

**Comment by McdonaldSeanp** [comment]
build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent_pkg-van-ship_daily-ad-hoc/143/

**Comment by McdonaldSeanp** [comment]
Passing build at: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent_pkg-van-ship_daily-ad-hoc/178/

**Pull request merged**
