### PR TITLE
(PA-474) Add deprecation warning 32 on 64bit Windows OS

### PR DESCRIPTION
**Pull request by glennsarti**
Windows Server 2003 is no longer a supported platform and while there is a
launch condition to stop installation, the warning dialog was still being
created in the MSI.  This commit removes the warning dialog itself and from the
relevant UI sequences.

It is intended to remove support for 32bit agents on 64bit Windows Operating
Systems beginning in 2017.  This commit adds a deprecation warning dialog when
installing a 32bit MSI on a 64bit Operating system.  This commit also adds in
the required, but disabled, code to block a 32bit MSI from being installed via a
 Launch Condition for later use.

### CODE REVIEW

**Comment by glennsarti** [comment]
The Travis fail was due to the ticket PA-474 being a private jira issue.

**Comment by glennsarti** [comment]
@McdonaldSeanp Should this be targetted against stable?

**Comment by McdonaldSeanp** [comment]
@glennsarti yes, in reality this should probably start from LTS-1.7, then get merged to stable, then master

**Comment by glennsarti** [comment]
@McdonaldSeanp Rebased.

**Comment by McdonaldSeanp** [comment]
👍

**Comment by Magisus** [comment]
This looks good 👍

**Pull request merged**
