### PR TITLE
(PA-159) Update huaweios build to use correct host triplet and arch

### PR DESCRIPTION
**Pull request by ScottGarman**
While investigating how Debian strips cross-compiled packages, I
realized we've been using the wrong host triplet for Debian powerpc.
The correct triplet should be powerpc-linux-gnu. This also changes
the arch from ppc to powerpc, another fix to follow Debian's naming
scheme.

### CODE REVIEW

**Comment by mckern** [comment]
This appears to be internally sane and consistent. Do we need to make that change anywhere else?

**Comment by ScottGarman** [comment]
Don't merge it just yet, I need to do a final shakedown test first.

**Comment by mckern** [comment]
We have labels now!

**Comment by underscorgan** [comment]
This looks reasonable

**Comment by underscorgan** [comment]
:+1:

**Pull request merged**
