### PR TITLE
Cherry pick of Fedora 25 platform addition to p-a stable

### PR DESCRIPTION
**Pull request by ScottGarman**

### CODE REVIEW

**Comment by ScottGarman** [comment]
Note: Travis failure is just due to the RE ticket number not being public.

**Comment by MosesMendoza** [comment]
@ScottGarman is this needed because these commits originally landed on master but are desired for stable? If so, given our merge strategy, I think the ideal path is to cherry-pick these back to stable and then merge up again stable => master (even though the commits are no-ops). Ideally we aren't merging master to stable.

**Comment by ScottGarman** [comment]
@MosesMendoza yeah, sorry, I was using the wrong terminology. These are cherry picks from master.

**Comment by MosesMendoza** [comment]
Ah, brilliant. thanks @ScottGarman

**Comment by MosesMendoza** [comment]
Do we have a Puppet Agent ticket for Fedora 25 addition? Seems like we might as well, and it would address the travis issue.

**Comment by ScottGarman** [comment]
@MosesMendoza it's not that we're missing a ticket number for the fedora 25 platform addition, it's that the RE ticket referenced in the second commit which adds the platform to build_data.yaml is internal.

**Comment by MosesMendoza** [comment]
👍

**Comment by ScottGarman** [comment]
It turns out we don't want Fedora 25 in the stable CI pipelines, so I'm closing this PR.

**Pull request closed without merging**
