### PR TITLE
(PA-1990) migrate nuget from nexus to artifactory

### PR DESCRIPTION
**Pull request by sarameisburger**
We are migrating everything over from nexus to artifactory. This commit changes the url for the nuget build repository and uses the artifactory/nuget api

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
jenkins please test this on windows2012r2-64a

**Comment by McdonaldSeanp** [comment]
"(1/7) PR Tests Kick-off — Step 1 Failed" is a red herring. An experimental job was left on.

Please consider a passing run of the other kick off to be a pass

**Comment by McdonaldSeanp** [comment]
@sarameisburger can you please migrate the RE ticket to the PA project?

**Comment by sarameisburger** [comment]
@McdonaldSeanp https://tickets.puppetlabs.com/browse/PA-1990 is this right?

**Comment by McdonaldSeanp** [comment]
@sarameisburger perfect. If you update your commit message with the new ticket number travis will pass.

**Comment by McdonaldSeanp** [comment]
jenkins please test this on windows2012r2-64a

**Pull request merged**
