### PR TITLE
(FACT-2027) Added facter-ng as a component

### PR DESCRIPTION
**Pull request by sebastian-miclea**

### CODE REVIEW

**Comment by mihaibuzgau** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,debian9-64a,debian9-32a,debian10-64a,fedora28-64a,fedora29-64a,windows2016-64a,windows2019-64a,centos6-64a,centos6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a

**Comment by gimmyxd** [comment]
👍  changes look good, we can merge it when the build is passing

**Comment by mihaibuzgau** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,debian9-64a,debian9-32a,debian10-64a,fedora28-64a,fedora29-64a,windows2016-64a,windows2019-64a,centos6-64a,centos6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a

**Comment by sebastian-miclea** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,debian9-64a,debian9-32a,debian10-64a,fedora28-64a,fedora29-64a,windows2016-64a,windows2019-64a,centos6-64a,centos6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a

**Pull request merged**
