### PR TITLE
(RE-9003) Bump vanagon to latest version

### PR DESCRIPTION
**Pull request by demophoon**

### CODE REVIEW

**Comment by demophoon** [comment]
I'm currently testing this through a local run of Vanagon to make sure that this bump doesn't break anything.

**Comment by Magisus** [comment]
We're currently floating on master: https://github.com/puppetlabs/puppet-agent/blob/master/Gemfile#L13 I just got a big PR merged to fix all the deprecation warnings too.

**Comment by demophoon** [comment]
@Magisus Thanks for doing that 😃
Just making sure, Master doesn't get merged back down into 1.10.x correct?

**Comment by demophoon** [comment]
I was able to get a built el-7-x86_64 artifact out of my local testing

**Comment by Magisus** [comment]
No it doesn't. This is effectively a backport. We probably want this one to float too, to match the other two branches?

**Comment by demophoon** [comment]
👍 I'll change that out here

**Pull request merged**
