### PR TITLE
(PA-4448) Adds Fedora 36 (x86-64) support

### PR DESCRIPTION
**Pull request by mhashizume**

### CODE REVIEW

**Comment by mhashizume** [comment]
jenkins please test this on fedora36-64

**Comment by mhashizume** [comment]
jenkins please test this on fedora36-64

**Comment by mhashizume** [comment]
jenkins please test this on fedora36-64

**Review by cthorn42 — APPROVED** [review]
Looks good to me, CI job passed with the recent changes.

**Pull request merged**
