### PR TITLE
(PA-1864) Add Fedora 28 platform definition

### PR DESCRIPTION
**Pull request by caseywilliams**

### CODE REVIEW

**Comment by caseywilliams** [comment]
I'll build this in an ad-hoc pipeline, since PR testing won't allocate an f28 vm yet -- blocking until then.

**Comment by caseywilliams** [comment]
[Here's a successful acceptance run](https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/189/) with changes from https://github.com/puppetlabs/puppet/pull/6895 -- merging is blocked on that PR.

**Comment by caseywilliams** [comment]
I'm blocking this again for now, pending some more testing -- the acceptance test changes here can be improved.

**Comment by caseywilliams** [comment]
Okay, this seems to work fine now with more minimal acceptance changes: [example run](https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/190/).

**Comment by branan** [comment]
:+1: from me

**Pull request merged**
