### PR TITLE
(maint) Cosmetic Updates

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Looks like you pulled in a merge up from master as well?

**Comment by melissa** [comment]
I have no idea what just happened

**Comment by MikaelSmith** [comment]
I'm not sure what happened to the branch, but it looks like this PR will bring back the changes from https://github.com/puppetlabs/puppet-agent/pull/504.

**Comment by MikaelSmith** [comment]
Needs a rebase now.

**Pull request merged**
