### PR TITLE
(maint) Bump FacterNg to 4.0.2

### PR DESCRIPTION
**Pull request by sebastian-miclea**

### CODE REVIEW

**Comment by sebastian-miclea** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,debian9-64a,debian9-32a,debian10-64a,fedora28-64a,fedora29-64a,windows2016-64a,windows2019-64a,centos6-64a,centos6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a

**Comment by sebastian-miclea** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,debian9-64a,debian9-32a,debian10-64a,fedora28-64a,fedora29-64a,windows2016-64a,windows2019-64a,centos6-64a,centos6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a

**Comment by sebastian-miclea** [comment]
jenkins please test this on redhat7-64a,redhat7-POWERa

**Comment by sebastian-miclea** [comment]
jenkins please test this on redhat7-64a,redhat7-POWERa,redhat7-AARCH64a

**Comment by sebastian-miclea** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,debian9-64a,debian9-32a,debian10-64a,fedora28-64a,fedora29-64a,windows2016-64a,windows2019-64a,centos6-64a,centos6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a

**Comment by sebastian-miclea** [comment]
jenkins please test this on osx1012-64a,osx1013-64a,osx1014-64a,debian9-64a,debian9-32a,debian10-64a,fedora28-64a,fedora29-64a,windows2016-64a,windows2019-64a,centos6-64a,centos6-32a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a

**Comment by gimmyxd** [comment]
to be merged after: https://github.com/puppetlabs/puppet-runtime/pull/279

**Pull request merged**
