### PR TITLE
(PA-950) Remove OSX clang patches and bump cpp-hocon

### PR DESCRIPTION
**Pull request by Magisus**
This commit removes patches to the OSX libc++ headers introduced in
RE-7667. The bug fixed by those patches has been avoided by changes in
cpp-hocon, brought in by the version bump to that component.

### CODE REVIEW

**Comment by Magisus** [comment]
Successful build: https://jenkins.puppetlabs.com/view/puppet-agent/view/ad%20hoc/job/platform_puppet-agent_pkg-van-ship_manual-ad-hoc/479/

**Comment by geoffnichols** [comment]
I was involved in the original addition of these patches and am 👍  on removing them.

**Comment by ScottGarman** [comment]
:+1:

**Comment by branan** [comment]
I'm :+1:, since the underlying hocon issue is fixed

**Pull request merged**
