### PR TITLE
(PA-5029) Remove platform file for Max OS 10.15

### PR DESCRIPTION
**Pull request by shubhamshinde360**

### CODE REVIEW

**Review by mhashizume — APPROVED** [review]

**Comment by joshcooper** [comment]
Hi @shubhamshinde360 we try to avoid introducing merge commits into feature branches. Instead you'll want to rebase your feature branch onto the latest upstream and then force push to your feature branch. Something like:

```
git fetch upstream
git checkout PA-5029-remove-platform-file
git reset --hard 42d8e0a54efc6417f415fffb9b6986877a7d3eed
git rebase upstream/main
git push -f origin HEAD
```

**Comment by joshcooper** [comment]
Also we no longer automatically merge from puppet-agent#7.x to main, so you'll want to create a second PR and target `puppet-agent#main` to remove osx 10.15. Easiest to cherry-pick the commit like:

```
git checkout -b PA-5029-remove-platform-file_main
git cherry-pick 42d8e0a54efc6417f415fffb9b6986877a7d3eed
git push origin HEAD
```

**Comment by shubhamshinde360** [comment]
Thanks @joshcooper, @mhashizume 
I have rebased the branch with 7.x

**Review by joshcooper — APPROVED** [review]

**Comment by joshcooper** [comment]
@shubhamshinde360 let me know when the PR for `main` is ready and I'll merge that

**Comment by shubhamshinde360** [comment]
Hey @joshcooper,
Seems we won't be needing these commits in main since main already has these changes made under the following commits.
https://github.com/puppetlabs/puppet-agent/commit/c651a67e22a512b8efcc9a96c2b01fc9a900d825
https://github.com/puppetlabs/puppet-agent/commit/9d1db6b2a675a35efeb95280b0684b1ed3fdc4a2

**Pull request merged**
