### PR TITLE
(PA-3336) move pxp-agent to its own project

### PR DESCRIPTION
**Pull request by gimmyxd**

### CODE REVIEW

**Comment by gimmyxd** [comment]
dependes on: https://github.com/puppetlabs/pxp-agent-vanagon/pull/1

**Comment by gimmyxd** [comment]
depends on: https://github.com/puppetlabs/ci-job-configs/pull/7233

**Comment by gimmyxd** [comment]
TODO: fix docker builds

**Comment by gimmyxd** [comment]
Jenkins please test this,pxp-agent on windows2019-64a

**Comment by gimmyxd** [comment]
Jenkins please test this,pxp-agent on windows2019-64a

**Review by ciprianbadescu — APPROVED** [review]

**Pull request merged**
