### PR TITLE
1.8.0 release candidate rebased

### PR DESCRIPTION
**Pull request by MosesMendoza**
(maint) Merge conflict resolution fixups

    After a difficult recent merge conflict resolution, we accidentally lost
    several changes we intended to keep. This commit is the result of a manual
    reconciliation between what we intend to ship as Puppet Agent 1.8.0 (originally
    cut from Puppet Agent/master) with the Puppet Agent stable branch.

### CODE REVIEW

**Comment by MosesMendoza** [comment]
@Magisus @branan can you review? especially build/test steps in compiled components? Several changes in there it seems. I also intended to retain the changes from #887 in which we disable curl on cisco-wrlinux

@Iristyle would you mind taking a look as well? particularly windows-specific patches that may have changed. 

We're basically checking that
a) this has everything we _want_ to ship that changed between 1.7.1 and current HEAD of master
b) this does not accidentally reverse anything that originally landed after 1.7.1 on stable (intended for release in 1.8.0) but was never merged up to master
c) this does not accidentally introduce any changes to stable from master that we do not intend to ship in 1.8.0, most notably #871

**Comment by MosesMendoza** [comment]
Also, just for context, the intention I believe (assuming this PR is satisfactory) is to
1) merge this PR to stable
2) generate builds from HEAD of _stable_ for manual package validation
3) assuming satisfactory automated and manual validation, tag the same SHA from (2) (i.e., HEAD of stable after the merge of this PR) as 1.8.0
4) generate builds for release from said 1.8.0 tag
5) merge stable to master (electing to keep master's current config component sha's, not those from this PR)

**Comment by Magisus** [comment]
So then, we plan to continue to not use a release branch? If we don't make one, we need to make sure to communicate (e.g. to @joshcooper) that _nothing_ can land on stable, notably https://github.com/puppetlabs/facter/pull/1461, unless we want to disable component promotions.

**Comment by joshcooper** [comment]
@Magisus thanks for heads up. I'll wait on PA related PRs until I hear from you all.

**Comment by Magisus** [comment]
This looks correct, as far as I can tell. All the switchable Ruby bits seem to have been transferred over correctly, the component tags are correct, all the gettext-related gems are present and correctly support switchable Ruby, building curl is correctly skipped on Cisco, and the "run tests as part of check" looks like it does on master. I definitely think someone else should also give this a pass, but 👍  from me.

**Comment by Magisus** [comment]
This ran green through the ad-hoc pipeline here https://jenkins.puppetlabs.com/view/puppet-agent/view/ad%20hoc/job/platform_puppet-agent_init-van-int_suite-manual-ad-hoc/416/

**Comment by Magisus** [comment]
A new Puppet SHA got promoted, so we crated a release branch without that commit and retargeted this PR at that branch.

**Comment by MosesMendoza** [comment]
Glad this got merged, looks like we're good to go. The downside of doing it this way is that we already had a public branch called `1.8.0-release` and deleted it, and then created a new one with a different history - effectively the same as force pushing to a public branch.

Another way to accomplish the intended effect I think (release without the extra puppet sha update) would have been to merge this manually to the command line, fixing the puppet.json conflict, and tag the commit `64cbc2c` after the merge.

**Pull request merged**
