### PR TITLE
(RE-9003) Bump vanagon to 0.13.1

### PR DESCRIPTION
**Pull request by demophoon**

### CODE REVIEW

**Comment by Magisus** [comment]
Is it okay for this to wait till after the upcoming release (Monday or Tuesday)? Or do you need it sooner than that?

**Comment by demophoon** [comment]
We can definitely wait until Monday/Tuesday. This isn't blocking ci or anything, just getting us more information about builds

**Comment by Magisus** [comment]
Okay great. In the meantime, green test builds: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent_pkg-van-ship_daily-ad-hoc/58/

**Comment by ericwilliamson** [comment]
@Magisus now that puppet-agent has released, is this ok to go in? What other branches do we need to target to get all actively shipped versions?

**Comment by ericwilliamson** [comment]
> This change is already present in the other branches.

@Magisus The other change had a typo in the version number. We need 0.13.1, not 0.12.1, which is what all other branches have.

**Comment by Magisus** [comment]
Ah gotcha. Then this needs to be merged up to 5.0.x, then to master.

**Comment by ericwilliamson** [comment]
> Ah gotcha. Then this needs to be merged up to 5.0.x, then to master.

@Magisus Is that something that will happen with time from the agent team, or should we make the PR's? Also, mergeup or cherry-pick commits?

**Comment by Magisus** [comment]
We always merge up. I let the Platform OS team know they'd need to do merge-ups, but not sure if anyone did. I can get that process started.

**Pull request merged**
