### PR TITLE
(FACT-2158) Add puppet facts show test

### PR DESCRIPTION
**Pull request by florindragos**
test was previously testing facter -p

### CODE REVIEW

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Review by gimmyxd — APPROVED** [review]

**Pull request merged**
