### PR TITLE
(PA-229) Add xenial build targets

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by shermdog** [comment]
Built and tested against both targets.  I'm tempted to just push the button myself, but I'll behave and just :+1:

**Comment by melissa** [comment]
:-D it *should* be fine to merge this whenever, since nothing for xenial will be built until the pipelines are updated. But you actually tested the built artifact? It runs? Services are okay? I installed it, but that was it...

**Comment by shermdog** [comment]
This is my general smoke test:

```
root@shmoa23rqh0vin1:~# dpkg -i puppet-agent_1.4.0.45.gc7df24c-1xenial_amd64.deb 
Selecting previously unselected package puppet-agent.
(Reading database ... 63164 files and directories currently installed.)
Preparing to unpack puppet-agent_1.4.0.45.gc7df24c-1xenial_amd64.deb ...
Unpacking puppet-agent (1.4.0.45.gc7df24c-1xenial) ...
Setting up puppet-agent (1.4.0.45.gc7df24c-1xenial) ...
Created symlink from /etc/systemd/system/multi-user.target.wants/puppet.service to /lib/systemd/system/puppet.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/mcollective.service to /lib/systemd/system/mcollective.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/pxp-agent.service to /lib/systemd/system/pxp-agent.service.
Removed symlink /etc/systemd/system/multi-user.target.wants/pxp-agent.service.
Processing triggers for libc-bin (2.21-0ubuntu6) ...
root@shmoa23rqh0vin1:~# /opt/puppetlabs/puppet/bin/puppet status
{
  "is_alive": true,
  "version": "4.4.1"
}
root@shmoa23rqh0vin1:~# /opt/puppetlabs/puppet/bin/puppet resource service
service { 'accounts-daemon.service':
  ensure => 'running',
  enable => 'true',
}
service { 'apparmor':
  ensure => 'running',
  enable => 'true',
}
```

**Comment by melissa** [comment]
sweet!

**Comment by shermdog** [comment]
dude!

**Comment by melissa** [comment]
Currently also building on the ad hoc pipeline, but there's not beaker or beaker-hostgenerator support for xenial yet, so, we'll see where that fails... https://jenkins.puppetlabs.com/view/puppet-agent/view/ad%20hoc/

**Comment by melissa** [comment]
yeah, the ad hoc pipeline failed because we don't have beaker support for xenial yet

**Comment by stahnma** [comment]
@melissa can you add support to beaker? No idea how hard that is, but rock it! :metal:

**Comment by melissa** [comment]
I can try... it's scheduled in next weeks sprint for the QE team though

**Pull request merged**
