### PR TITLE
(PA-148) update component tags for 1.3.3 release

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
this will update tags for puppet (to 4.3.2)
hiera (to 3.0.6) and facter (to 3.1.4)

### CODE REVIEW

**Comment by kylog** [comment]
@McdonaldSeanp can you amend the commit message to fix the puppet version to 4.3.2. Also, i before the e in `hiera`. Thanks!!

**Comment by McdonaldSeanp** [comment]
@kylog Done =)

**Comment by kylog** [comment]
:+1:

**Comment by johnduarte** [comment]
:+1:

**Pull request merged**
